with games as (
    select
        app_id,
        name,
        release_date::date as release_date,
        estimated_owners,
        peak_ccu,
        required_age,
        price::numeric(10, 2) as price,
        discount,
        dlc_count,
        about_the_game,
        header_image,
        website,
        support_url,
        support_email,
        windows,
        mac,
        linux,
        metacritic_score,
        metacritic_url,
        user_score,
        positive,
        negative,
        score_rank,
        achievements,
        recommendations,
        notes,
        screenshots,
        movies
    from {{ ref('raw_games') }}
)

select
    games.app_id,
    games.name,
    games.release_date,
    owners.estimated_owners_id,
    games.peak_ccu,
    games.required_age,
    games.price,
    games.discount,
    games.dlc_count,
    games.about_the_game,
    games.header_image,
    games.website,
    games.support_url,
    games.support_email,
    games.windows,
    games.mac,
    games.linux,
    games.metacritic_score,
    games.metacritic_url,
    games.user_score,
    games.positive,
    games.negative,
    games.score_rank,
    games.achievements,
    games.recommendations,
    games.notes,
    games.screenshots,
    games.movies
from games
left join {{ ref('stg_estimated_owners') }} as owners
    on games.estimated_owners = owners.estimated_owners