{% macro apply_staging_identity() %}
    {% set identity_columns = {
        'stg_games': 'game_id',
        'stg_estimated_owners': 'estimated_owners_id',
        'stg_languages': 'language_id',
        'stg_developers': 'developer_id',
        'stg_publishers': 'publisher_id',
        'stg_categories': 'category_id',
        'stg_genres': 'genre_id',
        'stg_tags': 'tag_id',
        'stg_reviews': 'review_id'
    } %}
    {% set identity_column = identity_columns.get(model.name) %}
    {% if identity_column %}
        {{ return('alter table ' ~ this ~ ' add column ' ~ identity_column ~ ' integer generated by default as identity') }}
    {% endif %}
    {{ return('select 1') }}
{% endmacro %}