{% macro apply_mart_constraints() %}
    {% set identity_columns = {
        'dim_game': 'game_sk',
        'dim_estimated_owners': 'estimated_owners_sk',
        'dim_language': 'language_sk',
        'dim_developer': 'developer_sk',
        'dim_publisher': 'publisher_sk',
        'dim_category': 'category_sk',
        'dim_genre': 'genre_sk',
        'dim_tag': 'tag_sk',
        'fct_game_metrics': 'game_metrics_sk'
    } %}
    {% set identity_column = identity_columns.get(model.name) %}
    {% set statements = [] %}
    {% if identity_column %}
        {% do statements.append(
            'alter table ' ~ this ~ ' add column ' ~ identity_column ~ ' integer generated by default as identity'
        ) %}
    {% endif %}
    {% set primary_keys = {
        'dim_date': 'date_key',
        'dim_game': 'game_sk',
        'dim_estimated_owners': 'estimated_owners_sk',
        'dim_language': 'language_sk',
        'dim_developer': 'developer_sk',
        'dim_publisher': 'publisher_sk',
        'dim_category': 'category_sk',
        'dim_genre': 'genre_sk',
        'dim_tag': 'tag_sk',
        'fct_game_metrics': 'game_metrics_sk',
        'bridge_game_supported_language': 'game_sk, language_sk',
        'bridge_game_full_audio_language': 'game_sk, language_sk',
        'bridge_game_developer': 'game_sk, developer_sk',
        'bridge_game_publisher': 'game_sk, publisher_sk',
        'bridge_game_category': 'game_sk, category_sk',
        'bridge_game_genre': 'game_sk, genre_sk',
        'bridge_game_tag': 'game_sk, tag_sk'
    } %}
    {% set suffix = invocation_id[:6] %}
    {% do statements.append('alter table ' ~ this ~ ' drop constraint if exists ' ~ model.name ~ '_pk_' ~ suffix) %}
    {% do statements.append(
        'alter table ' ~ this ~ ' add constraint ' ~ model.name ~ '_pk_' ~ suffix ~ ' primary key (' ~ primary_keys[model.name] ~ ')'
    ) %}

    {% set foreign_keys = {
        'dim_game': [('date_key', 'dim_date', 'date_key')],
        'fct_game_metrics': [
            ('game_sk', 'dim_game', 'game_sk'),
            ('estimated_owners_sk', 'dim_estimated_owners', 'estimated_owners_sk')
        ],
        'bridge_game_supported_language': [
            ('game_sk', 'dim_game', 'game_sk'), ('language_sk', 'dim_language', 'language_sk')
        ],
        'bridge_game_full_audio_language': [
            ('game_sk', 'dim_game', 'game_sk'), ('language_sk', 'dim_language', 'language_sk')
        ],
        'bridge_game_developer': [
            ('game_sk', 'dim_game', 'game_sk'), ('developer_sk', 'dim_developer', 'developer_sk')
        ],
        'bridge_game_publisher': [
            ('game_sk', 'dim_game', 'game_sk'), ('publisher_sk', 'dim_publisher', 'publisher_sk')
        ],
        'bridge_game_category': [
            ('game_sk', 'dim_game', 'game_sk'), ('category_sk', 'dim_category', 'category_sk')
        ],
        'bridge_game_genre': [
            ('game_sk', 'dim_game', 'game_sk'), ('genre_sk', 'dim_genre', 'genre_sk')
        ],
        'bridge_game_tag': [
            ('game_sk', 'dim_game', 'game_sk'), ('tag_sk', 'dim_tag', 'tag_sk')
        ]
    } %}
    {% for child_column, parent_model, parent_column in foreign_keys.get(model.name, []) %}
        {% do statements.append(
            'alter table ' ~ this ~ ' drop constraint if exists ' ~ model.name ~ '_' ~ child_column ~ '_fk_' ~ suffix
        ) %}
        {% do statements.append(
            'alter table ' ~ this ~ ' add constraint ' ~ model.name ~ '_' ~ child_column ~ '_fk_' ~ suffix ~ ' foreign key (' ~ child_column ~ ') references ' ~ ref(parent_model) ~ ' (' ~ parent_column ~ ')'
        ) %}
    {% endfor %}

    {{ return(statements | join(';\n')) }}
{% endmacro %}
